# Copyright (c) Semi-ATE
# Distributed under the terms of the MIT License

# /py37/linux-64/maxiconda

{% set version = os.environ.get("MAXICONDA_ENV_RELEASE", "") %}

package:
  name: maxiconda
  version: {{ version }}

source: 
  path: .

build:
  number: 0  # fixed to 0

requirements:
  build:
    # python
    - python =3.7.10

  run:
    # python
    - python

    # primary packages:
    - matplotlib =3.4.2
    - numba =0.53.1
    - numpy =1.20.3
    - openpyxl =3.0.7
    - pandas =1.2.4
    - psutil =5.8.0
    - pyqt =5.12.3
    - qdarkstyle =3.0.2
    - qtawesome =1.0.2
    - regex =2021.4.4
    - requests =2.25.1
    - spyder-kernels =2.0.4
    - sqlalchemy =1.4.18
    - sqlite =3.35.5
    - tqdm =4.61.1
    
    # secondary packages:
    - _libgcc_mutex =0.1
    - _openmp_mutex =4.5
    - alsa-lib =1.2.3
    - backcall =0.2.0
    - backports =1.0
    - backports.functools_lru_cache =1.6.4
    - brotlipy =0.7.0
    - ca-certificates =2021.5.30
    - certifi =2021.5.30
    - cffi =1.14.5
    - chardet =4.0.0
    - cloudpickle =1.6.0
    - cryptography =3.4.7
    - cycler =0.10.0
    - dbus =1.13.6
    - decorator =5.0.9
    - et_xmlfile =1.0.1
    - expat =2.4.1
    - fontconfig =2.13.1
    - freetype =2.10.4
    - gettext =0.19.8.1
    - glib =2.68.3
    - glib-tools =2.68.3
    - greenlet =1.1.0
    - gst-plugins-base =1.18.4
    - gstreamer =1.18.4
    - icu =68.1
    - idna =2.10
    - importlib-metadata =4.5.0
    - ipykernel =5.5.5
    - ipython =7.24.1
    - ipython_genutils =0.2.0
    - jbig =2.1
    - jdcal =1.4.1
    - jedi =0.18.0
    - jpeg =9d
    - jupyter_client =6.1.12
    - jupyter_core =4.7.1
    - kiwisolver =1.3.1
    - krb5 =1.19.1
    - lcms2 =2.12
    - ld_impl_linux-64 =2.35.1
    - lerc =2.2.1
    - libblas =3.9.0
    - libcblas =3.9.0
    - libclang =11.1.0
    - libdeflate =1.7
    - libedit =3.1.20191231
    - libevent =2.1.10
    - libffi =3.3
    - libgcc-ng =9.3.0
    - libgfortran-ng =9.3.0
    - libgfortran5 =9.3.0
    - libglib =2.68.3
    - libgomp =9.3.0
    - libiconv =1.16
    - liblapack =3.9.0
    - libllvm10 =10.0.1
    - libllvm11 =11.1.0
    - libogg =1.3.4
    - libopenblas =0.3.15
    - libopus =1.3.1
    - libpng =1.6.37
    - libpq =13.3
    - libsodium =1.0.18
    - libstdcxx-ng =9.3.0
    - libtiff =4.3.0
    - libuuid =2.32.1
    - libvorbis =1.3.7
    - libwebp-base =1.2.0
    - libxcb =1.13
    - libxkbcommon =1.0.3
    - libxml2 =2.9.12
    - llvmlite =0.36.0
    - lz4-c =1.9.3
    - matplotlib-base =3.4.2
    - matplotlib-inline =0.1.2
    - mysql-common =8.0.25
    - mysql-libs =8.0.25
    - ncurses =6.2
    - nspr =4.30
    - nss =3.67
    - olefile =0.46
    - openjpeg =2.4.0
    - openssl =1.1.1k
    - parso =0.8.2
    - pcre =8.45
    - pexpect =4.8.0
    - pickleshare =0.7.5
    - pillow =8.2.0
    - pip =21.1.2
    - prompt-toolkit =3.0.19
    - pthread-stubs =0.4
    - ptyprocess =0.7.0
    - pycparser =2.20
    - pygments =2.9.0
    - pyopenssl =20.0.1
    - pyparsing =2.4.7
    - pyqt-impl =5.12.3
    - pyqt5-sip =4.19.18
    - pyqtchart =5.12
    - pyqtwebengine =5.12.1
    - pysocks =1.7.1
    - python-dateutil =2.8.1
    - python_abi =3.7
    - pytz =2021.1
    - pyzmq =22.1.0
    - qt =5.12.9
    - qtpy =1.9.0
    - readline =8.1
    - setuptools =49.6.0
    - six =1.16.0
    - tk =8.6.10
    - tornado =6.1
    - traitlets =5.0.5
    - typing_extensions =3.10.0.0
    - urllib3 =1.26.5
    - wcwidth =0.2.5
    - wheel =0.36.2
    - wurlitzer =2.1.0
    - xorg-libxau =1.0.9
    - xorg-libxdmcp =1.1.3
    - xz =5.2.5
    - zeromq =4.3.4
    - zipp =3.4.1
    - zlib =1.2.11
    - zstd =1.5.0
    
about:
  home: https://github.com/Semi-ATE/maxiconda-envs
  license: MIT
  license_file: ../../../../LICENSE
  summary: 'maxiconda meta package'
  dev_url: https://github.com/Semi-ATE/maxiconda-envs/blob/main/specs/primary_packages.yaml
extra:
  recipe-maintainers:
    - nerohmot
