# Copyright (c) Semi-ATE
# Distributed under the terms of the MIT License

# /py36/win-64/_spyder_

{% set version = os.environ.get("MAXICONDA_ENV_RELEASE", "") %}

package:
  name: _spyder_
  version: {{ version }}

source: 
  path: .

build:
  number: 0  # fixed to 0

requirements:
  build:
    # python
    - python =3.6.13

  run:
    # python
    - python

    # primary packages:
    - spyder =5.0.4
    - spyder-remote-client =0.0.4
    - spyder-screencast =0.0.12
    
    # secondary packages:
    - alabaster =0.7.12
    - appdirs =1.4.4
    - argh =0.26.2
    - arrow =1.1.0
    - astroid =2.5.6
    - async_generator =1.10
    - atomicwrites =1.4.0
    - attrs =21.2.0
    - autopep8 =1.5.6
    - babel =2.9.1
    - backcall =0.2.0
    - backports =1.0
    - backports.functools_lru_cache =1.6.4
    - bcrypt =3.2.0
    - binaryornot =0.4.4
    - black =21.5b2
    - bleach =3.3.0
    - brotlipy =0.7.0
    - ca-certificates =2021.5.30
    - certifi =2021.5.30
    - cffi =1.14.5
    - chardet =4.0.0
    - click =8.0.1
    - cloudpickle =1.6.0
    - colorama =0.4.4
    - cookiecutter =1.7.3
    - cryptography =3.4.7
    - dataclasses =0.8
    - decorator =5.0.9
    - defusedxml =0.7.1
    - diff-match-patch =20200713
    - docutils =0.17.1
    - entrypoints =0.3
    - ffmpeg =4.3.1
    - flake8 =3.8.4
    - future =0.18.2
    - icu =68.1
    - idna =2.10
    - ifaddr =0.1.7
    - imagesize =1.2.0
    - importlib-metadata =4.5.0
    - importlib_metadata =4.5.0
    - inflection =0.5.1
    - intervaltree =3.0.2
    - ipykernel =5.5.5
    - ipython =7.16.1
    - ipython_genutils =0.2.0
    - isort =5.8.0
    - jedi =0.17.2
    - jinja2 =2.11.3
    - jinja2-time =0.2.0
    - jpeg =9d
    - jsonschema =3.2.0
    - jupyter_client =6.1.12
    - jupyter_core =4.7.1
    - jupyterlab_pygments =0.1.2
    - keyring =23.0.1
    - lazy-object-proxy =1.6.0
    - libclang =11.1.0
    - libpng =1.6.37
    - libsodium =1.0.18
    - libspatialindex =1.9.3
    - markupsafe =1.1.1
    - mccabe =0.6.1
    - mistune =0.8.4
    - mypy_extensions =0.4.3
    - nbclient =0.5.3
    - nbconvert =6.0.7
    - nbformat =5.1.3
    - nest-asyncio =1.5.1
    - netifaces =0.10.9
    - numpydoc =1.1.0
    - openssl =1.1.1k
    - packaging =20.9
    - pandoc =2.14.0.2
    - pandocfilters =1.4.2
    - paramiko =2.7.2
    - parso =0.7.0
    - pathspec =0.8.1
    - pexpect =4.8.0
    - pickleshare =0.7.5
    - pip =21.1.2
    - pluggy =0.13.1
    - poyo =0.5.0
    - prompt-toolkit =3.0.19
    - psutil =5.8.0
    - pycodestyle =2.6.0
    - pycparser =2.20
    - pydocstyle =6.1.1
    - pyflakes =2.2.0
    - pygments =2.9.0
    - pylint =2.8.3
    - pyls-black =0.4.6
    - pyls-spyder =0.3.2
    - pynacl =1.4.0
    - pyopenssl =20.0.1
    - pyparsing =2.4.7
    - pyqt =5.12.3
    - pyqt-impl =5.12.3
    - pyqt5-sip =4.19.18
    - pyqtchart =5.12
    - pyqtwebengine =5.12.1
    - pyrsistent =0.17.3
    - pysocks =1.7.1
    - python-dateutil =2.8.1
    - python-jsonrpc-server =0.4.0
    - python-language-server =0.36.2
    - python-slugify =5.0.2
    - python_abi =3.6
    - pytz =2021.1
    - pywin32 =300
    - pywin32-ctypes =0.2.0
    - pyyaml =5.4.1
    - pyzmq =22.1.0
    - qdarkstyle =3.0.2
    - qscreencast =0.1.35
    - qstylizer =0.2.0
    - qt =5.12.9
    - qtawesome =1.0.2
    - qtconsole =5.1.0
    - qtpy =1.9.0
    - regex =2021.4.4
    - requests =2.25.1
    - rope =0.19.0
    - rtree =0.9.4
    - setuptools =49.6.0
    - six =1.16.0
    - snowballstemmer =2.1.0
    - sortedcontainers =2.4.0
    - sphinx =4.0.2
    - sphinxcontrib-applehelp =1.0.2
    - sphinxcontrib-devhelp =1.0.2
    - sphinxcontrib-htmlhelp =2.0.0
    - sphinxcontrib-jsmath =1.0.1
    - sphinxcontrib-qthelp =1.0.3
    - sphinxcontrib-serializinghtml =1.1.5
    - spyder-kernels =2.0.4
    - sqlite =3.35.5
    - testpath =0.5.0
    - text-unidecode =1.3
    - textdistance =4.2.1
    - three-merge =0.1.1
    - tinycss2 =1.1.0
    - toml =0.10.2
    - tornado =6.1
    - traitlets =4.3.3
    - typed-ast =1.4.3
    - typing_extensions =3.10.0.0
    - ujson =4.0.2
    - unidecode =1.2.0
    - urllib3 =1.26.5
    - vc =14.2
    - vs2015_runtime =14.28.29325
    - watchdog =2.1.2
    - wcwidth =0.2.5
    - webencodings =0.5.1
    - wheel =0.36.2
    - win_inet_pton =1.1.0
    - wincertstore =0.2
    - wrapt =1.12.1
    - yaml =0.2.5
    - yapf =0.31.0
    - zeroconf =0.31.0
    - zeromq =4.3.4
    - zipp =3.4.1
    - zlib =1.2.11
    
about:
  home: https://github.com/Semi-ATE/maxiconda-envs
  license: MIT
  license_file: ../../../../LICENSE
  summary: '_spyder_ meta package'
  dev_url: https://github.com/Semi-ATE/maxiconda-envs/blob/main/specs/primary_packages.yaml
extra:
  recipe-maintainers:
    - nerohmot
