name: CD

on:
  release:
    types: [created]

jobs:
  build_and_upload:
    name: ${{ matrix.SUBDIR }}
    runs-on: ubuntu-latest
    env:
      SUBDIR: ${{ matrix.SUBDIR }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - SUBDIR: win-64
          - SUBDIR: linux-64
          - SUBDIR: linux-aarch64
          - SUBDIR: osx-64
          - SUBDIR: osx-arm64
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10

    - name: build and upload meta-packages
      shell: bash -l {0}
      run: |
        export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        mkdir build
        cd build
        python -u ../scripts/maxiconda.py --build --upload $SUBDIR

  digest:
    runs-on: ubuntu-latest
    needs: build_and_upload
    steps:
    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10

    - name: Create the summary
      shell: bash -l {0}
      run: |
        echo export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        python -u scripts/digest.py --build ${GITHUB_REF##*/}

    - name: Upload the summary to release assets
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["maxiconda-envs.xlsx"]'
