name: CD

on: [push, pull_request]

jobs:
  create:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
