name: CD

on:
  release:
    types: [created]

jobs:
  build:
    name: ${{ matrix.SUBDIR }}
    runs-on: ${{ matrix.OS_IMAGE }}
    env:
      SUBDIR: ${{ matrix.SUBDIR }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS_IMAGE: ubuntu-latest
            SUBDIR: linux-64

          - OS_IMAGE: ubuntu-latest
            SUBDIR: linux-aarch64

          - OS_IMAGE: macos-latest
            SUBDIR: osx-64

          - OS_IMAGE: macos-latest
            SUBDIR: osx-arm64

          - OS_IMAGE: windows-latest
            SUBDIR: win-64
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install micromamba & environment
      uses: mamba-org/setup-micromamba@v2.0.3
      with:
        environment-file: environment.yml

    - name: build meta-packages
      shell: bash -l {0}
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        conda config --set channel_priority false
        mkdir build
        cd build
        python -u ../scripts/maxiconda.py --build $SUBDIR

    - name: Upload meta-packages to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.SUBDIR }}_packages
        path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install micormamba & environment
      uses: mamba-org/setup-micromamba@v2.0.3
      with:
        environment-file: environment.yml

    - name: Download meta-packages from artifacts
      uses: actions/download-artifact@v4

    - name: Move packages into place
      shell: bash -l {0}
      run: |
        mkdir ./build
        for dir in ./*/; do
          dir="${dir%/}"
          dir="${dir##*/}"
          if [[ "$dir" == *_packages ]]; then
            subdir=${dir%_packages}
            source_dir="./${subdir}_packages/${subdir}"
            destination_dir="./build/"
            copy="cp -rv $source_dir $destination_dir"
            echo $copy
            $copy
            remove="rm -rf $dir"
            echo $remove
            $remove
          fi
        done

    - name: Upload to anaconda.org
      shell: bash -l {0}
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        python -u scripts/release.py

    - name: Create the summary
      shell: bash -l {0}
      run: |
        echo export MAXICONDA_ENV_RELEASE=${GITHUB_REF##*/}
        python -u scripts/digest.py --build ${GITHUB_REF##*/}

    - name: Upload the summary and the specs to release assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["maxiconda-envs.xlsx", "specs.yaml"]'

