name: CI

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  solve_and_test:
    name: ${{ matrix.TARGET_CONDA_SUBDIR }}
    runs-on: ubuntu-latest
    env:
      TARGET_CONDA_SUBDIR: ${{ matrix.TARGET_CONDA_SUBDIR }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET_CONDA_SUBDIR: win-64
          - TARGET_CONDA_SUBDIR: linux-64
          - TARGET_CONDA_SUBDIR: linux-aarch64
          - TARGET_CONDA_SUBDIR: osx-64
          - TARGET_CONDA_SUBDIR: osx-arm64
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10
        
    - name: Solve and test-build meta-packages
      shell: bash -l {0}
      run: |
        echo $(TARGET_CONDA_SUBDIR)
        mkdir build
        cd build
        python -u ../scripts/maxiconda.py --solve --build

    - name: Upload build meta-packages
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.CONDA_SUBDIR }}-meta-packages
        path: build/

    - name: Remove build meta-packages from file system
      shell: bash -l {0}
      run: rm -rf build

    - name: Commit recipes
      shell: bash -l {0}
      run: |
        export DATE=$(date +'%A %B %d, %Y')
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "$(git status --porcelain)"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "git stash -u"
          git stash -u
          echo "git pull"
          git pull
          echo "git stash pop"
          git stash pop
          echo "git add -A"
          git add -A
          echo "git commit -m \"$DATE (${{ matrix.os }})\""
          git commit -m "$DATE (${{ matrix.os }})"
        else
          echo "Nothing to commit ($DATE)"
          git pull
        fi  

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs
