name: Build recipes

on: [push, pull_request]

jobs:
  create:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-envs
        environment-file: environment.yml
        channel-priority: strict

    - name: Build packages
      shell: bash -l {0}
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        MAXICONDA_ENV_RELEASE: "0.0.1"
      run: |
        python -u scripts/build.py
