name: Continuous Integration

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  solve_and_test:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.VM }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: win-64
            VM: windows-latest            
          - OS: linux-64
            VM: ubuntu-latest
          - OS: osx-64
            VM: macos-latest
          - OS: linux-aarch64
            VM: ubuntu-latest
            DOCKER_IMG: condaforge/linux-anvil-aarch64
          - OS: osx-arm64
            VM: macos-latest
            DOCKER_IMG: xyz      
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-envs
        environment-file: environment.yaml
        channel-priority: strict

    - name: Solve and test-build target environments
      shell: bash -l {0}
      env:
        OS: ${{ matrix.OS }}
        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
      run: |
        if [[ "$OS" == "linux-aarch64" ]]; then
          echo "Solving Environments for linux-aarch64"
        elif [[ "$OS" == "osx-arm64" ]]; then
          echo "Solving Environments for osx-arm64"
        else
          echo ">>>>> Solving Environments for $OS <<<<<"
          python -u scripts/solve.py
          echo ">>>>> Test Build Environments for $OS <<<<<"
          python -u scripts/build.py --test
        fi

    - name: Commit files
      shell: bash -l {0}
      run: |
        something_changed=`git diff-index --quiet HEAD` || true
        if [[ -n "$something_changed" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git stash -u
          git pull
          git stash pop
          git add -A
          git commit -m "Update packages ${{ matrix.OS }}"
        else
          echo "Nothing to commit"
        fi  

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs
