name: CI

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  solve_and_build:
    name: ${{ matrix.SUBDIR }}
    runs-on: ${{ matrix.OS_IMAGE }}
    env:
      SUBDIR: ${{ matrix.SUBDIR }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS_IMAGE: ubuntu-latest
            SUBDIR: linux-64

          - OS_IMAGE: ubuntu-latest
            SUBDIR: linux-aarch64

          - OS_IMAGE: macos-latest
            SUBDIR: osx-64

          - OS_IMAGE: macos-latest
            SUBDIR: osx-arm64

          - OS_IMAGE: windows-latest
            SUBDIR: win-64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install micromamba & environment
      uses: mamba-org/setup-micromamba@v2.0.3
      with:
        environment-file: environment.yml

    - name: Import requests in micromamba environment (bash)
      run: python -c "import requests"
      shell: bash -el {0}

    - name: Solve and test-build meta-packages
      shell: bash -l {0}
      run: |
        conda config --set channel_priority false
        mkdir build
        cd build
        python -u ../scripts/maxiconda.py --solve --build $SUBDIR

    - name: Upload solved recipes
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.SUBDIR }}_recipes
        path: recipes/${{ matrix.SUBDIR }}/

    - name: Upload build packages
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.SUBDIR }}_packages
        path: build/

  consolidate:
    runs-on: ubuntu-latest
    needs: solve_and_build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

    - name: Install micormamba & environment
      uses: mamba-org/setup-micromamba@v2.0.3

    - name: Download *ALL* Build Artifacts
      uses: actions/download-artifact@v4

    - name: Remove build packages
      shell: bash -l {0}
      run: rm -rf *_packages/

    - name: Move recipes into place
      shell: bash -l {0}
      run: |
        for dir in ./*/; do
          dir="${dir%/}"
          dir="${dir##*/}"
          if [[ "$dir" == *_recipes ]]; then
            target=${dir%_recipes}
            destination_dir="./recipes/${target}/"
            source_dir="./${target}_recipes"
            if [ ! -d "$destination_dir" ]; then
              mkdir $destination_dir
            fi
            move="cp -rf $source_dir/* $destination_dir"
            echo $move
            $move
            remove="rm -rf $source_dir"
            echo $remove
            $remove
          fi
        done

    - name: Commit recipes
      shell: bash -l {0}
      run: |
        export DATE=$(date +'%A %B %d, %Y')
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "$(git status --porcelain)"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "git stash -u"
          git stash -u
          echo "git pull"
          git pull
          echo "git stash pop"
          git stash pop
          echo "git add -A"
          git add -A
          echo "git commit -m \"$DATE\""
          git commit -m "$DATE"
        else
          echo "Nothing to commit ($DATE)"
          git pull
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs
