name: Nightly Solver

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  solve_and_test:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.VM }}
    env:
      OS: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: win-64
            VM: windows-latest
          - OS: linux-64
            VM: ubuntu-latest
          - OS: osx-64
            VM: macos-latest
          - OS: linux-aarch64
            VM: ubuntu-latest
            DOCKER_IMG: condaforge/linux-anvil-aarch64
          - OS: osx-arm64
            VM: macos-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

    - name: Set up conda environment
      if: ${{ env.OS != 'linux-aarch64' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-envs
        environment-file: environment.yaml
        channel-priority: strict

    - name: Solve and test-build target environments
      shell: bash -l {0}
      env:
        OS: ${{ matrix.OS }}
        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
      run: |
        if [[ "$OS" == "linux-aarch64" ]]; then
          echo "Cross solving environments for linux-aarch64 (no test build)"
          export CONDA_SUBDIR="linux-aarch64"
          python -u scripts/maxiconda.py --solve
        elif [[ "$OS" == "osx-arm64" ]]; then
          echo "Cross solving environments for osx-arm64 (no test build)"
          export CONDA_SUBDIR="osx-arm64"
          python -u scripts/maxiconda.py --solve
        else
          python -u scripts/maxiconda.py --solve --build
        fi
        
    - name: Commit files
      shell: bash -l {0}
      run: |
        export DATE=$(date +'%A %B %d, %Y')
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "$(git status --porcelain)"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "git stash -u"
          git stash -u
          echo "git pull"
          git pull
          echo "git stash pop"
          git stash pop
          echo "git add -A"
          git add -A
          echo "git commit -m \"$DATE (${{ matrix.os }})\""
          git commit -m "$DATE (${{ matrix.os }})"
        else
          echo "Nothing to commit ($DATE)"
        fi  

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs
